---
- hosts: all
  become: true

  tasks:
  - name: Ensure a locale exists
    locale_gen:
      name: pt_BR.UTF-8
      state: present
  
  - name: set locale
    command: /usr/sbin/update-locale LANG=pt_BR.UTF-8 LC_ALL=pt_BR.UTF-8

  - name: Add repositories
    apt_repository: repo='ppa:deadsnakes/ppa' state=present

  - name: ensure unzip is installed
    apt: pkg=unzip update_cache=yes

  - name: ensure python3.6 is installed
    apt: pkg=python3.6 update_cache=yes

  - name: ensure python3.6 is installed
    apt: pkg=python3-pip update_cache=yes

  - name: copy your folder using a work around
    unarchive: src=mess.zip dest=/home/vagrant/
  
  - name: copy pipfile
    copy:
      src: Pipfile
      dest: /home/vagrant/Pipfile

  - name: copy pipfile lock
    copy:
      src: Pipfile.lock
      dest: /home/vagrant/Pipfile.lock

  - name: copy requirements
    copy:
      src: requirements.txt
      dest: /home/vagrant/requirements.txt

  - name: install dependencies
    command: chdir=/home/vagrant python3.6 -m pip install -r requirements.txt

  - name: run name server
    shell: python3.6 -m Pyro4.naming >/dev/null 2>&1 &